### ISSUE TITLE
BUG: Dropped support for old filters with feature

### ISSUE THREAD

**Issue by tomaszdurka** [wepublish/wepublish#601]
As I understand it's a breaking-change as we stopped support for old filters which are used (?).
@antkiewiczk can you please check it? I presume its connected with your last work.

Quoting @roosnic1 

This release has a critical bug. The subscription filters have been changed/enhanced. In the file `packages/api/src/db/subscription.ts` the new filters have been added and the existing ones are still there. But in the file `packages/api-db-mongodb/src/db/subscription.ts` the old filters like `paidUntil` are not handled anymore. 

The following code:
```typescript
const subscriptions = await dbAdapter.subscription.getSubscriptions({
  cursor: {type: InputCursorType.None},
  limit: {count: 100, type: LimitType.First, skip},
  order: SortOrder.Ascending,
  sort: SubscriptionSort.CreatedAt,
  filter: {
    paidUntil: {
      comparison: DateFilterComparison.GreaterThanOrEqual,
      date: migrationDate
    }
  }
})
```
 results in the following error:
```bash
error MongoError: $and/$or/$nor must be a nonempty array
    at MessageStream.messageHandler (/home/koki/Development/tsri/juanita/website/node_modules/@tsri-wepublish/api-db-mongodb/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (events.js:314:20)
    at MessageStream.EventEmitter.emit (domain.js:506:15)
    at processIncomingData (/home/koki/Development/tsri/juanita/website/node_modules/@tsri-wepublish/api-db-mongodb/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/koki/Development/tsri/juanita/website/node_modules/@tsri-wepublish/api-db-mongodb/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at Socket.ondata (_stream_readable.js:718:22)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
  ok: 0,
  code: 2,
  codeName: 'BadValue'
}
```

Tsüri.ch uses the `dbAdapter.subscription.getSubscriptions(...)` method with the existing filters in multiple places. It can't be that those filters disappear just like that without any deprecation.

**Comment by Itrulia** [comment]
I noticed that too yesterday when migrating the subscription to prisma. Are they used by Tsri? I saw some being used in the paymentContext and changed them to use prisma directly instead.
